# Generated by Django 4.2.7 on 2023-12-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookCollection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbook',
            old_name='brand',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='addbook',
            name='quantity',
        ),
    ]
