# Generated by Django 4.2.7 on 2023-12-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCollection', '0002_rename_brand_addbook_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
