# Generated by Django 4.2.7 on 2023-12-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersaccount',
            name='birth_date',
        ),
    ]
